// -------------------------------------------------------------
// 
// File Name: C:\Users\Sertan\Desktop\Simulink_Model\Verilog_Codes\LIF_Neuron_Model\LIF_Neuron_Model.v
// Created: 2025-07-05 12:00:49
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.0001
// Target subsystem base rate: 0.0001
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.0001
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// g                             ce_out        0.0001
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: LIF_Neuron_Model
// Source Path: LIF_Neuron_Model
// Hierarchy Level: 0
// Model version: 1.22
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module LIF_Neuron_Model
          (clk,
           reset,
           clk_enable,
           g_e,
           g_i,
           ce_out,
           g);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] g_e;  // sfix16_En8
  input   signed [15:0] g_i;  // sfix16_En8
  output  ce_out;
  output  signed [15:0] g;  // sfix16_En8


  wire signed [15:0] Subsystem_out1;  // sfix16_En8


  Subsystem u_Subsystem (.clk(clk),
                         .reset(reset),
                         .enb(clk_enable),
                         .g_e(g_e),  // sfix16_En8
                         .g_i(g_i),  // sfix16_En8
                         .g(Subsystem_out1)  // sfix16_En8
                         );

  assign g = Subsystem_out1;

  assign ce_out = clk_enable;

endmodule  // LIF_Neuron_Model

