// -------------------------------------------------------------
// 
// File Name: C:\Users\Sertan\Desktop\Simulink_Model\Verilog_Codes\Improved_Network_Model\INa.v
// Created: 2025-07-05 12:04:45
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: INa
// Source Path: Improved_Network_Model/INa
// Hierarchy Level: 1
// Model version: 1.37
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module INa
          (In1,
           In2,
           g);


  input   signed [31:0] In1;  // sfix32_En22
  input   signed [15:0] In2;  // sfix16_En8
  output  signed [15:0] g;  // sfix16_En8


  wire switch_compare_1;
  wire signed [15:0] Constant1_out1;  // sfix16_En8
  wire switch_compare_1_1;
  wire signed [15:0] Constant_out1;  // sfix16_En8
  wire signed [15:0] Switch_out1;  // sfix16_En8
  wire signed [15:0] Constant2_out1;  // sfix16_En8
  wire signed [15:0] Switch1_out1;  // sfix16_En8


  assign switch_compare_1 = In1 >= 32'sb00000110010000000000000000000000;



  assign Constant1_out1 = 16'sb0000000000000000;



  assign switch_compare_1_1 = In2 >= 16'sb0000000000000000;



  assign Constant_out1 = 16'sb0001111000000000;



  assign Switch_out1 = (switch_compare_1 == 1'b0 ? Constant1_out1 :
              Constant_out1);



  assign Constant2_out1 = 16'sb0000000000000000;



  assign Switch1_out1 = (switch_compare_1_1 == 1'b0 ? Switch_out1 :
              Constant2_out1);



  assign g = Switch1_out1;

endmodule  // INa

