// -------------------------------------------------------------
// 
// File Name: C:\Users\Sertan\Desktop\Simulink_Model\Verilog_Codes\Improved_Network_Model\INb.v
// Created: 2025-07-05 12:04:45
// 
// Generated by MATLAB 23.2, HDL Coder 23.2, and Simulink 23.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: INb
// Source Path: Improved_Network_Model/INb
// Hierarchy Level: 1
// Model version: 1.37
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module INb
          (In1_0,
           In1_1,
           In1_2,
           In1_3,
           In1_4,
           In1_5,
           In1_6,
           In1_7,
           g_0,
           g_1,
           g_2,
           g_3,
           g_4,
           g_5,
           g_6,
           g_7);


  input   signed [31:0] In1_0;  // sfix32_En22
  input   signed [31:0] In1_1;  // sfix32_En22
  input   signed [31:0] In1_2;  // sfix32_En22
  input   signed [31:0] In1_3;  // sfix32_En22
  input   signed [31:0] In1_4;  // sfix32_En22
  input   signed [31:0] In1_5;  // sfix32_En22
  input   signed [31:0] In1_6;  // sfix32_En22
  input   signed [31:0] In1_7;  // sfix32_En22
  output  signed [15:0] g_0;  // sfix16_En8
  output  signed [15:0] g_1;  // sfix16_En8
  output  signed [15:0] g_2;  // sfix16_En8
  output  signed [15:0] g_3;  // sfix16_En8
  output  signed [15:0] g_4;  // sfix16_En8
  output  signed [15:0] g_5;  // sfix16_En8
  output  signed [15:0] g_6;  // sfix16_En8
  output  signed [15:0] g_7;  // sfix16_En8


  wire switch_compare_1;
  wire signed [15:0] Constant1_out1;  // sfix16_En8
  wire signed [15:0] Constant_out1;  // sfix16_En8
  wire signed [15:0] Switch_out1_0;  // sfix16_En8
  wire switch_compare_2;
  wire signed [15:0] Switch_out1_1;  // sfix16_En8
  wire switch_compare_3;
  wire signed [15:0] Switch_out1_2;  // sfix16_En8
  wire switch_compare_4;
  wire signed [15:0] Switch_out1_3;  // sfix16_En8
  wire switch_compare_5;
  wire signed [15:0] Switch_out1_4;  // sfix16_En8
  wire switch_compare_6;
  wire signed [15:0] Switch_out1_5;  // sfix16_En8
  wire switch_compare_7;
  wire signed [15:0] Switch_out1_6;  // sfix16_En8
  wire switch_compare_8;
  wire signed [15:0] Switch_out1_7;  // sfix16_En8


  assign switch_compare_1 = In1_0 >= 32'sb00110010000000000000000000000000;



  assign Constant1_out1 = 16'sb0000000000000000;



  assign Constant_out1 = 16'sb0001111000000000;



  assign Switch_out1_0 = (switch_compare_1 == 1'b0 ? Constant1_out1 :
              Constant_out1);



  assign g_0 = Switch_out1_0;

  assign switch_compare_2 = In1_1 >= 32'sb00110010000000000000000000000000;



  assign Switch_out1_1 = (switch_compare_2 == 1'b0 ? Constant1_out1 :
              Constant_out1);



  assign g_1 = Switch_out1_1;

  assign switch_compare_3 = In1_2 >= 32'sb00110010000000000000000000000000;



  assign Switch_out1_2 = (switch_compare_3 == 1'b0 ? Constant1_out1 :
              Constant_out1);



  assign g_2 = Switch_out1_2;

  assign switch_compare_4 = In1_3 >= 32'sb00110010000000000000000000000000;



  assign Switch_out1_3 = (switch_compare_4 == 1'b0 ? Constant1_out1 :
              Constant_out1);



  assign g_3 = Switch_out1_3;

  assign switch_compare_5 = In1_4 >= 32'sb00110010000000000000000000000000;



  assign Switch_out1_4 = (switch_compare_5 == 1'b0 ? Constant1_out1 :
              Constant_out1);



  assign g_4 = Switch_out1_4;

  assign switch_compare_6 = In1_5 >= 32'sb00110010000000000000000000000000;



  assign Switch_out1_5 = (switch_compare_6 == 1'b0 ? Constant1_out1 :
              Constant_out1);



  assign g_5 = Switch_out1_5;

  assign switch_compare_7 = In1_6 >= 32'sb00110010000000000000000000000000;



  assign Switch_out1_6 = (switch_compare_7 == 1'b0 ? Constant1_out1 :
              Constant_out1);



  assign g_6 = Switch_out1_6;

  assign switch_compare_8 = In1_7 >= 32'sb00110010000000000000000000000000;



  assign Switch_out1_7 = (switch_compare_8 == 1'b0 ? Constant1_out1 :
              Constant_out1);



  assign g_7 = Switch_out1_7;

endmodule  // INb

